version: '3.9'
services:
  rabbitmq:
    hostname: lazyrabbit
    image: rabbitmq:4.1.0-alpine
    ports:
      - "5672:5672"
    networks:
      - rabbitmq-cluster
networks:
  rabbitmq-cluster:
    driver: bridge
